baseURL = 'https://thurunany.github.io/projetos-porti/'
languageCode = 'en-us'
title = 'Meu portifolio'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

ignoreLogs = ["warning-goldmark-raw-html"]